### ISSUE TITLE
Guidelines for images?

### ISSUE THREAD

**Issue by eyedeekay** [J-tt/r-i2p-wiki#5]
I've been writing some tutorials on how to set-up tunnels to existing applications using java-i2p, and have found it most helpful to include pictures, step-by-step, of how tunnels are configured. Ideally, I'd like to push these tutorials to the wiki here, but I have some concerns about how the images will be displayed on the wiki with the current layout, as they are quite wide and the layout is quite narrow. Also the images include text, so my cropping/shrinking options may be limited. [This one](https://eyedeekay.github.io/i2p-i2pd-sshsetup/) would be a good example of what I mean. I'm conflicted, because my goal here is to familiarize people with the ways i2p can be configured, show them in context, and add them to easy-to-find resources, so not being ready to add it to the wiki bugs me. What are your thoughts on this?

**Comment by J-tt** [comment]
From what I can see images embed relatively alright, my suggestion for large images is to add them like so:


[![Alt text](https://eyedeekay.github.io/i2p-i2pd-sshsetup/standard.png)](https://eyedeekay.github.io/i2p-i2pd-sshsetup/standard.png)

If you hover over the image it is a link to it, this allows people to click on the image and get a larger view, I think this is a decent solution.

**Comment by eyedeekay** [comment]
OK, good enough for me.
